### ISSUE TITLE
Missing dependency: Cython

### ISSUE THREAD

**Issue by strpeter** [FZJ-INM1-BDA/pytiff#12]
I found out after installing pytiff that the package cython was missing as a dependency because I did not install it previously.

The error message (under Windows and Python 3.7.2) with pytiff-0.8.0 said "Cython modules not available". Could you please make sure that during the installation the installer setup checks the availabillity of cython?

**Comment by pglock** [comment]
The wheel for python 3.7 seems to be broken. It's not that cython is needed, but that the pytiff cython files were not built correctly with appveyor. @kgoebbels or me will try to fix the wheel.

If you are using anaconda, you may try to build pytiff yourself. 

Steps: 
- conda install -y libtiff numpy cython
- clone the repo, cd pytiff
- copy `PathToAnaconda\Library\lib\tiff.lib` into the the repo folder
- python setup.py install

**Comment by pglock** [comment]
Updated to version 0.8.1. The  wheel for python 3.7 should be working now.
