### ISSUE TITLE
test_data/bigtif_example_tiled.tif is not a Bigtiff

### ISSUE THREAD

**Issue by stuarteberg** [FZJ-INM1-BDA/pytiff#3]
I was looking for an example of a 'tiled' Bigtiff file, so naturally I opened `test_data/bigtif_example_tiled.tif` from this repo:

```python
In [90]: hex( ord( open('test_data/bigtif_example_tiled.tif', 'r').read(4)[2] ) )
Out[90]: '0x2a'
```

Whoops, the third byte of a Bigtiff file should be `0x2b`, not `0x2a`.\[1]

\[1]: http://bigtiff.org/

**Comment by pglock** [comment]
Thanks! `test_data/bigtif_example_tiled.tif` is now a Bigtiff file. 
Pytiff has now a function to check if a tiff file is a Bigtiff.

```python
In [2]: pytiff.is_bigtiff("bigtif_example_tiled.tif")
Out[2]: True
```
