### ISSUE TITLE
Problems with sliced arrays and method = 'scanline'

### ISSUE THREAD

**Issue by Sifeiros** [FZJ-INM1-BDA/pytiff#7]
I encountered this proplem as I tried to save a 3D np.array as a stack of tifs. 

What I essentially did was this:

```
img_stack = np.zeros((100,100,50), dtype = 'uint8')
img_stack[30:60,30:60,20:30] = 255

for ind in range(50):
    img_slice = img_stack[:,:,ind]
    with pytiff.Tiff(file_path.format(ind), 'w') as handle:
        handle.write(img_slice, method='scanline')
```

This produces same strange artefacts, when used on a regular image stack. On this particular 'image stack' it should produce all black tifs, if the problem is reproduceable on other machines. 

The problem does not occur, when the flag method is set to 'tile'. 
I fixed this py replacing the line
`img_slice = img_stack[:,:,ind]`
with
`img_slice = img_stack[:,:,ind].copy()`

**Comment by pglock** [comment]
The array written to disk must be c contiguous. If you slice along a dimension other than the first one, this is no longer the case.

If you use the flag 'tile', it is padded to the correct tile size internally. This also ensures that the data is contiguous. For the flag 'scanline' this is not the case.

I updated the method to make scanline check if the data is contiguous. If that's not the case, the data is **copied** to a contiguous array.
